name: .NET build and deploy

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  DOTNET_SOLUTION: backlog-bot-csharp-template.slnx
  DOTNET_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 #v6
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.DOTNET_SOLUTION }}

    - name: Build solution
      run: dotnet build ${{ env.DOTNET_SOLUTION }} --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore

    - name: Test solution
      run: dotnet test ${{ env.DOTNET_SOLUTION }} --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build --verbosity normal
